version: "3"
services:
  server:
    image: dotnet7_webapi:1.0.0
    container_name: "${CON_WEB_SERVER}"
    depends_on:
      - account_db
      - active_user_db
    ports:
      - "80:80"
    networks:
      - net_random_dice
    environment:
      - CONN_STR_ACCOUNT=Server=${CON_ACCOUNT_DB};uid=${MYSQL_USER};pwd=${MYSQL_PASSWORD};database=${MYSQL_DATABASE}
      - CONN_STR_ACTIVE_USER_DB=${CON_ACTIVE_USER_DB}:${ACTIVE_USER_DB_PORT},password=${ACTIVE_USER_DB_PASS},ssl=False,abortConnect=False

  account_db:
    
    image: mysql
    container_name: "${CON_ACCOUNT_DB}"
    ports:
      - "${MYSQL_PORT}:3306"
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./account_db/conf.d:/etc/mysql/conf.d
      - ./account_db/initdb.d/:/docker-entrypoint-initdb.d/
    expose:
      - 3306
    networks:
      - net_random_dice
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  active_user_db:
    image: redis
    container_name: ${CON_ACTIVE_USER_DB}
    command: redis-server --port ${ACTIVE_USER_DB_PORT}
    environment:
      - REDIS_PASSWORD=1q2w3e4r
    ports:
      - "${ACTIVE_USER_DB_PORT}:6379"
    labels:
      - "name=redis"
      - "mode=standalone"
    expose:
      - 6379
    networks:
      - net_random_dice

networks:
  net_random_dice:
    driver: bridge

volumes:
  vol_accout_db:
    driver: local
    driver_opts:
      device: ${HOME}/var/data/account_db
      o: bind
      type: none